// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Login() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<html><head><title>Login</title><style>\r\n\t\t\t\tbody {\r\n\t\t\t\t\tfont-family: Arial, sans-serif;\r\n\t\t\t\t\tbackground-color: #f4f4f4;\r\n\t\t\t\t\tdisplay: flex;\r\n\t\t\t\t\tjustify-content: center;\r\n\t\t\t\t\talign-items: center;\r\n\t\t\t\t\theight: 100vh;\r\n\t\t\t\t\tmargin: 0;\r\n\t\t\t\t}\r\n\t\t\t\t.login-container {\r\n\t\t\t\t\tbackground-color: #fff;\r\n\t\t\t\t\tpadding: 2rem;\r\n\t\t\t\t\tborder-radius: 8px;\r\n\t\t\t\t\tbox-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);\r\n\t\t\t\t\twidth: 300px;\r\n\t\t\t\t\ttext-align: center;\r\n\t\t\t\t}\r\n\t\t\t\t.login-container h2 {\r\n\t\t\t\t\tmargin-bottom: 1rem;\r\n\t\t\t\t\tcolor: #333;\r\n\t\t\t\t}\r\n\t\t\t\t.login-container input {\r\n\t\t\t\t\twidth: 100%;\r\n\t\t\t\t\tpadding: 0.75rem;\r\n\t\t\t\t\tmargin-bottom: 1rem;\r\n\t\t\t\t\tborder: 1px solid #ddd;\r\n\t\t\t\t\tborder-radius: 4px;\r\n\t\t\t\t\tbox-sizing: border-box;\r\n\t\t\t\t}\r\n\t\t\t\t.login-container button {\r\n\t\t\t\t\twidth: 100%;\r\n\t\t\t\t\tpadding: 0.75rem;\r\n\t\t\t\t\tborder: none;\r\n\t\t\t\t\tbackground-color: #007bff;\r\n\t\t\t\t\tcolor: #fff;\r\n\t\t\t\t\tborder-radius: 4px;\r\n\t\t\t\t\tfont-size: 1rem;\r\n\t\t\t\t\tcursor: pointer;\r\n\t\t\t\t\ttransition: background-color 0.3s ease;\r\n\t\t\t\t}\r\n\t\t\t\t.login-container button:hover {\r\n\t\t\t\t\tbackground-color: #0056b3;\r\n\t\t\t\t}\r\n\t\t\t</style></head><body><div class=\"login-container\"><h2>Login</h2><form action=\"/auth/login-post\" method=\"post\"><input type=\"text\" name=\"username\" placeholder=\"Username\" required> <input type=\"password\" name=\"password\" placeholder=\"Password\" required> <button type=\"submit\">Login</button></form></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
